/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.PopupMenu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import model.ArtistiDB;
import service.ServiceController;
import javax.swing.*;
import model.UsersDB;

/**
 *
 * @author student
 */
public class MainFrame extends javax.swing.JFrame {

    DefaultListModel<ArtistiDB> model;
    private JPopupMenu menu;
    public MainFrame() {
        initComponents();
        menu = new JPopupMenu();
        JMenuItem pm = new JMenuItem("Afisare Melodii");
        pm.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
                ArtistiDB x = (ArtistiDB) jList1.getSelectedValue();
              //  System.out.println(x.toString());
                
                new MelodiiFrame(x);
            }
        });
        JMenuItem pm2 = new JMenuItem("Adaugare Melodi");
        
        pm2.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
            }
        });
        JMenuItem pm3 = new JMenuItem("Stergere Melodie");
        pm3.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                ArtistiDB x = (ArtistiDB) jList1.getSelectedValue();
                ServiceController.getInstance().deleteArtist(x);
            }
        });
       
        model = new DefaultListModel<>();
        jList1.setModel(model);
        afisareArtisti();
        
        
        
        menu.add(pm);
        menu.add(pm2);
        menu.add(pm3);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public void afisareArtisti(){
        List<ArtistiDB> artisti = ServiceController.getInstance().getAllArtisti();
        model.clear();
        for (ArtistiDB a : artisti) {
            model.addElement(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jMenu1.setText("Optiuni");

        jMenuItem1.setText("Delogare");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit Application");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        
        /*PopupMenu listPopup = new PopupMenu();
        String x = (String)jList1.getSelectedValue();
        
        if (x.equals(evt.BUTTON3)) {
        listPopup.show(jList1, evt.getX(), evt.getY() );
        System.out.println("test");
        }*/
        
        jList1.setSelectedIndex(jList1.locationToIndex(evt.getPoint()));
	//	System.out.println(jList1.getSelectedIndex());
	menu.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jList1MouseClicked

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
