/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.util.List;
import javax.swing.DefaultListModel;
import model.ArtistiDB;
import model.MelodiiDB;
import model.UsersDB;
import service.ServiceController;

/**
 *
 * @author student
 */
public class MelodiiFrame extends javax.swing.JFrame {

    DefaultListModel<MelodiiDB> model;
    ArtistiDB u;
    public MelodiiFrame(ArtistiDB u) {
        this.u = u;
        initComponents();
        model = new DefaultListModel<>();
        jList1.setModel(model);
        System.out.println("constructor Melodii");
        afisareMelodii();
        
        
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
     public void afisareMelodii(){
        List<MelodiiDB> mel = ServiceController.getInstance().getAllMelodii(u);
         System.out.println(mel);
        
        model.clear();
         for (MelodiiDB m : mel) {
             System.out.println(m);
             model.addElement(m);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
