/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Carduri;
import beans.Clienti;
import controllers.Controller;
import java.util.List;
import javax.swing.DefaultListModel;
import obspattern.CardListener;

/**
 *
 * @author Laur
 */
public class MainFrame extends javax.swing.JFrame {
    private DefaultListModel<Clienti> model1 = new DefaultListModel<Clienti>();
    private DefaultListModel<Carduri> model2 = new DefaultListModel<Carduri>();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jList1.setModel(model1);
        jList2.setModel(model2);
        fillClientList();
        Controller.getInstance().getC1().addCardListener(
                new CardListener() {
            @Override
            public void cardModificat(Carduri c) {
                fillCardList(c.getId());
            }
        }
        );
    }

    private void fillClientList(){
        List<Clienti> clienti = Controller.getInstance().getClienti();
        model1.clear();
        for(Clienti c: clienti) model1.addElement(c);
    }
    
    private void fillCardList(Integer id){
        List<Carduri> carduri = Controller.getInstance().getCarduriFromClient(id);
        model2.clear();
        for(Carduri c: carduri) model2.addElement(c);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jSplitPane1.setRightComponent(jScrollPane2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        Clienti client = (Clienti) jList1.getSelectedValue();
        fillCardList(client.getId());
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        if(evt.getClickCount()==2){
            Carduri card = (Carduri) jList2.getSelectedValue();
            UpdateCardFrame f = new UpdateCardFrame(card);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jList2MouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
